# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Initial disk space
      run: df -h
    - name: Cleanup
      run: |
        sudo deb-get install du-dust
        dust /
    - name: Final disk space
      run: df -h
