# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'tests/**'

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Tests
      run: echo Tada
