name: Renovate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
    - 'renovate/**'

jobs:
  export:
    name: Export requirements
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run poetry export
        run: tox run -e poetry-lock

  ci-tests:
    needs:
      - export
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
