# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Renovate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.jujuignore'
      - 'LICENSE'
      - '**.md'

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
