name: Update renovate exports and libs

on:
  pull_request:
    branches:
      - 'renovate/*'

jobs:
  lint:
    name: export
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run linters
        run: tox run -e poetry-lock

jobs:
  needs:
    - export
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
